name: ASCII Generator

on: push

jobs:
    Generare-ASCII:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: List the files
              run: ls -ltra

            - name: Run the Script
              run: |
                chmod +x ascii.sh
                ./ascii.sh

            